services:
  cli:
    image: ghcr.io/codemarc/gridsvcs/motd:0.0.3
    restart: unless-stopped
    build:
      context: .
      tags:
        - ghcr.io/codemarc/gridsvcs/motd:latest
    environment:
      - GSDATA=data
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/gridsvcs/motd/data
      - ./logs:/gridsvcs/motd/logs
    ports:
       - 3000:3000

