apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    field.cattle.io/publicEndpoints: '[{"port":32345,"protocol":"TCP","serviceName":"gridsvcs:motd-nodeport","allNodes":true}]'
  creationTimestamp: "2024-07-26T12:27:31Z"
  generation: 18
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-gridsvcs-motd
  name: motd
  namespace: gridsvcs
  resourceVersion: "52525"
  uid: b1011fb5-a81b-4993-a728-be9e9adb84b6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-gridsvcs-motd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-gridsvcs-motd
      namespace: gridsvcs
    spec:
      containers:
      - env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: OPENAI_API_KEY
              name: apikeys
              optional: false
        image: ghcr.io/codemarc/gridsvcs/motd:latest
        imagePullPolicy: Always
        name: motd
        ports:
        - containerPort: 3000
          name: motdport
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: codemarc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-07-26T13:45:27Z"
    lastUpdateTime: "2024-07-26T13:45:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-07-26T12:27:31Z"
    lastUpdateTime: "2024-07-26T14:18:43Z"
    message: ReplicaSet "motd-666dbcb78d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 18
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
